version: '3.8'

services:
  db-test:
    image: postgres:16.9-bullseye
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banners_test
    container_name: tp-banners-db-test
    volumes:
      - ./postgres_data_test:/var/lib/postgresql/data
